# Generated by Django 5.2.15 on 2026-07-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notificacion_destinatario_notificacion_leida'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='fecha_limite',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
