# Generated by Django 5.2.15 on 2026-07-06 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ticket_fecha_limite'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='areas',
            field=models.ManyToManyField(blank=True, related_name='tecnicos', to='core.categoria', verbose_name='Áreas asignadas'),
        ),
    ]
