# Generated by Django 5.2.15 on 2026-07-08 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usuario_areas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='activo',
            new_name='is_active',
        ),
    ]
