# Generated by Django 5.2.15 on 2026-07-11 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_renombrar_activo_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'area',
            },
        ),
        migrations.AddField(
            model_name='categoria',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categorias', to='core.area'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='areas',
            field=models.ManyToManyField(blank=True, related_name='tecnicos', to='core.area', verbose_name='Áreas asignadas'),
        ),
    ]
